### ISSUE TITLE
no error log, won't run.

### ISSUE THREAD

**Issue by tounsicorp** [jixxed/ed-odyssey-materials-helper#385]
App no longer runs, no assistance, prompt closes too fast to catch the error and..??  no logs??

**Comment by jixxed** [comment]
try backing up and removing your app settings %localappdata%\odyssey-materials-helper

**Comment by jixxed** [comment]
logs are in %localappdata%\Elite Dangerous Odyssey Materials Helper Launcher\log

**Comment by Banjomel** [comment]
I have this problem. Log says :

2024-08-22 14:42:40 ERROR n.j.e.domain.ApplicationState - error acquiring lock
java.io.FileNotFoundException: C:\Users\Mel\AppData\Local\odyssey-materials-helper\lock (Access is denied)
	at java.base/java.io.FileOutputStream.open0(Native Method)
	at java.base/java.io.FileOutputStream.open(Unknown Source)
	at java.base/java.io.FileOutputStream.<init>(Unknown Source)
	at java.base/java.io.FileOutputStream.<init>(Unknown Source)
	at nl.jixxed.eliteodysseymaterials/nl.jixxed.eliteodysseymaterials.domain.ApplicationState.isLocked(Unknown Source)
	at nl.jixxed.eliteodysseymaterials/nl.jixxed.eliteodysseymaterials.Main.main(Unknown Source)

Regards,
Mel

**Comment by jixxed** [comment]
You can check for the existence of the file. It seems to be related to the app being ran with elevated privileges. You should never run the app as Admin. The app will ask you when it needs more privileges.  You might consider backing up C:\Users\Mel\AppData\Local\odyssey-materials-helper and then removing the folder to see if that resolves your issue.

**Comment by Banjomel** [comment]
Thanks for your reply. I tried running as Admin because after the software updates it goes to 'running' and then the animation just disappears  with nothing further happening. I've installed and uninstalled several times to no avail.

This last install a few minutes ago gave this error in the log (I think it's the same as the previous error). I did not elevate this to running as admin.

2024-08-22 19:24:40 ERROR n.j.e.domain.ApplicationState - error acquiring lock
java.io.FileNotFoundException: C:\Users\Mel\AppData\Local\odyssey-materials-helper\lock (Access is denied)
      at java.base/java.io.FileOutputStream.open0(Native Method)
      at java.base/java.io.FileOutputStream.open(Unknown Source)
      at java.base/java.io.FileOutputStream.<init>(Unknown Source)
      at java.base/java.io.FileOutputStream.<init>(Unknown Source)
      at nl.jixxed.eliteodysseymaterials/nl.jixxed.eliteodysseymaterials.domain.ApplicationState.isLocked(Unknown Source)
      at nl.jixxed.eliteodysseymaterials/nl.jixxed.eliteodysseymaterials.Main.main(Unknown Source)

Regards,
Mel
________________________________

**Comment by Banjomel** [comment]
Hi,

Removing that folder allowed the program to run. Thanks for the solution.

Do I need to copy that folder back ?

Regards,
Mel
________________________________

**Comment by jixxed** [comment]
reinstalling the app does nothing, because all the application settings are persisted between installations. that is the folder you just removed, effectively making your current installation a clean installation. The folder contains all your wishlists and loadouts that you created. if you didn't have any or don't care about them, you can delete the backup. otherwise you would have to carefully replace the contents of the relevant files. don't replace the files, since that might copy back wrong permissions. all would need to be done while the app isn't running.
