### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Shamon11** [jixxed/ed-odyssey-materials-helper#392]
https://disk.yandex.ru/i/QSk3hAcCzBicyA

**Comment by Yur1j** [comment]
Same to me 
![image](https://github.com/user-attachments/assets/8462a0c0-692f-4715-a59c-1c737f332180)

**Comment by StasAbrosimov** [comment]
Workaround is next: 

Clear your folder %localappdata%/odyssey-materials-helper and reinstall this app.
It help for me.

**Comment by AgentPunto** [comment]
2024-08-17 12:04:35 ERROR n.j.e.FXApplication - Failed to initialize the UI
java.lang.ArrayIndexOutOfBoundsException: Index 7 out of bounds for length 7
	at org.apache.commons.csv@1.7.0/org.apache.commons.csv.CSVRecord.get(Unknown Source)
	at nl.jixxed.eliteodysseymaterials/nl.jixxed.eliteodysseymaterials.helper.CSVResourceBundle.lambda$new$2(Unknown Source)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.base/java.util.stream.ForEachOps$ForEachTask.compute(Unknown Source)
	at java.base/java.util.concurrent.CountedCompleter.exec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.helpComplete(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.helpComplete(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinTask.awaitDone(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinTask.join(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinTask.invoke(Unknown Source)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateParallel(Unknown Source)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateParallel(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline.forEach(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(Unknown Source)
	at nl.jixxed.eliteodysseymaterials/nl.jixxed.eliteodysseymaterials.helper.CSVResourceBundle.lambda$new$3(Unknown Source)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(Unknown Source)
	at nl.jixxed.eliteodysseymaterials/nl.jixxed.eliteodysseymaterials.helper.CSVResourceBundle.<init>(Unknown Source)
	at nl.jixxed.eliteodysseymaterials/nl.jixxed.eliteodysseymaterials.helper.CSVResourceBundle.lambda$getResourceBundle$4(Unknown Source)
	at java.base/java.util.HashMap.computeIfAbsent(Unknown Source)
	at nl.jixxed.eliteodysseymaterials/nl.jixxed.eliteodysseymaterials.helper.CSVResourceBundle.getResourceBundle(Unknown Source)
	at nl.jixxed.eliteodysseymaterials/nl.jixxed.eliteodysseymaterials.service.LocaleService.getLocalizedString(Unknown Source)
	at nl.jixxed.eliteodysseymaterials/nl.jixxed.eliteodysseymaterials.service.LocaleService.getLocalizedStringForLocale(Unknown Source)
	at nl.jixxed.eliteodysseymaterials/nl.jixxed.eliteodysseymaterials.service.LocaleService.getLocalizedStringForCurrentLocale(Unknown Source)
	at nl.jixxed.eliteodysseymaterials/nl.jixxed.eliteodysseymaterials.enums.HorizonsBlueprintType.toString(Unknown Source)
	at com.fasterxml.jackson.databind@2.17.2/com.fasterxml.jackson.databind.util.EnumResolver.constructUsingToString(Unknown Source)
	at com.fasterxml.jackson.databind@2.17.2/com.fasterxml.jackson.databind.deser.BasicDeserializerFactory.createEnumDeserializer(Unknown Source)
	at com.fasterxml.jackson.databind@2.17.2/com.fasterxml.jackson.databind.deser.DeserializerCache._createDeserializer2(Unknown Source)
	at com.fasterxml.jackson.databind@2.17.2/com.fasterxml.jackson.databind.deser.DeserializerCache._createDeserializer(Unknown Source)
	at com.fasterxml.jackson.databind@2.17.2/com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCache2(Unknown Source)
	at com.fasterxml.jackson.databind@2.17.2/com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCacheValueDeserializer(Unknown Source)
	at com.fasterxml.jackson.databind@2.17.2/com.fasterxml.jackson.databind.deser.DeserializerCache.findValueDeserializer(Unknown Source)
	at com.fasterxml.jackson.databind@2.17.2/com.fasterxml.jackson.databind.DeserializationContext.findNonContextualValueDeserializer(Unknown Source)
	at com.fasterxml.jackson.databind@2.17.2/com.fasterxml.jackson.databind.deser.BeanDeserializerBase.resolve(Unknown Source)
	at com.fasterxml.jackson.databind@2.17.2/com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCache2(Unknown Source)
	at com.fasterxml.jackson.databind@2.17.2/com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCacheValueDeserializer(Unknown Source)
	at com.fasterxml.jackson.databind@2.17.2/com.fasterxml.jackson.databind.deser.DeserializerCache.findValueDeserializer(Unknown Source)
	at com.fasterxml.jackson.databind@2.17.2/com.fasterxml.jackson.databind.DeserializationContext.findContextualValueDeserializer(Unknown Source)
	at com.fasterxml.jackson.databind@2.17.2/com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.createContextual(Unknown Source)
	at com.fasterxml.jackson.databind@2.17.2/com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.createContextual(Unknown Source)
	at com.fasterxml.jackson.databind@2.17.2/com.fasterxml.jackson.databind.DeserializationContext.handlePrimaryContextualization(Unknown Source)
	at com.fasterxml.jackson.databind@2.17.2/com.fasterxml.jackson.databind.deser.BeanDeserializerBase.resolve(Unknown Source)
	at com.fasterxml.jackson.databind@2.17.2/com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCache2(Unknown Source)
	at com.fasterxml.jackson.databind@2.17.2/com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCacheValueDeserializer(Unknown Source)
	at com.fasterxml.jackson.databind@2.17.2/com.fasterxml.jackson.databind.deser.DeserializerCache.findValueDeserializer(Unknown Source)
	at com.fasterxml.jackson.databind@2.17.2/com.fasterxml.jackson.databind.DeserializationContext.findContextualValueDeserializer(Unknown Source)
	at com.fasterxml.jackson.databind@2.17.2/com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.createContextual(Unknown Source)
	at com.fasterxml.jackson.databind@2.17.2/com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.createContextual(Unknown Source)
	at com.fasterxml.jackson.databind@2.17.2/com.fasterxml.jackson.databind.DeserializationContext.handlePrimaryContextualization(Unknown Source)
	at com.fasterxml.jackson.databind@2.17.2/com.fasterxml.jackson.databind.deser.BeanDeserializerBase.resolve(Unknown Source)
	at com.fasterxml.jackson.databind@2.17.2/com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCache2(Unknown Source)
	at com.fasterxml.jackson.databind@2.17.2/com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCacheValueDeserializer(Unknown Source)
	at com.fasterxml.jackson.databind@2.17.2/com.fasterxml.jackson.databind.deser.DeserializerCache.findValueDeserializer(Unknown Source)
	at com.fasterxml.jackson.databind@2.17.2/com.fasterxml.jackson.databind.DeserializationContext.findRootValueDeserializer(Unknown Source)
	at com.fasterxml.jackson.databind@2.17.2/com.fasterxml.jackson.databind.ObjectMapper._findRootDeserializer(Unknown Source)
	at com.fasterxml.jackson.databind@2.17.2/com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(Unknown Source)
	at com.fasterxml.jackson.databind@2.17.2/com.fasterxml.jackson.databind.ObjectMapper.readValue(Unknown Source)
	at com.fasterxml.jackson.databind@2.17.2/com.fasterxml.jackson.databind.ObjectMapper.readValue(Unknown Source)
	at nl.jixxed.eliteodysseymaterials/nl.jixxed.eliteodysseymaterials.service.ships.LegacyModuleService.loadModules(Unknown Source)
	at nl.jixxed.eliteodysseymaterials/nl.jixxed.eliteodysseymaterials.templates.settings.sections.HorizonsShips.lambda$updateModules$13(Unknown Source)
	at java.base/java.util.Optional.map(Unknown Source)
	at nl.jixxed.eliteodysseymaterials/nl.jixxed.eliteodysseymaterials.templates.settings.sections.HorizonsShips.updateModules(Unknown Source)
	at nl.jixxed.eliteodysseymaterials/nl.jixxed.eliteodysseymaterials.templates.settings.sections.HorizonsShips.createHorizonsShipsModuleList(Unknown Source)
	at nl.jixxed.eliteodysseymaterials/nl.jixxed.eliteodysseymaterials.templates.settings.sections.HorizonsShips.initComponents(Unknown Source)
	at nl.jixxed.eliteodysseymaterials/nl.jixxed.eliteodysseymaterials.templates.settings.sections.HorizonsShips.<init>(Unknown Source)
	at nl.jixxed.eliteodysseymaterials/nl.jixxed.eliteodysseymaterials.templates.settings.SettingsTab.initComponents(Unknown Source)
	at nl.jixxed.eliteodysseymaterials/nl.jixxed.eliteodysseymaterials.templates.settings.SettingsTab.<init>(Unknown Source)
	at nl.jixxed.eliteodysseymaterials/nl.jixxed.eliteodysseymaterials.templates.ApplicationLayout.initComponents(Unknown Source)
	at nl.jixxed.eliteodysseymaterials/nl.jixxed.eliteodysseymaterials.templates.ApplicationLayout.<init>(Unknown Source)
	at nl.jixxed.eliteodysseymaterials/nl.jixxed.eliteodysseymaterials.FXApplication.lambda$start$1(Unknown Source)
	at javafx.graphics@21.0.1/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at javafx.graphics@21.0.1/com.sun.javafx.application.PlatformImpl.lambda$runLater$11(Unknown Source)
	at javafx.graphics@21.0.1/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(Unknown Source)
	at javafx.graphics@21.0.1/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at javafx.graphics@21.0.1/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

**Comment by StasAbrosimov** [comment]
Further investigation led me to the fact that the application began to handle Russian localization poorly.
When activating this localization in the settings through the menu, nothing happens.
If the setting was enabled before the last update, then we get the error presented above.

I will write further for those who use Russian localization....

Что бы не потерять все остальные настройки и сохранить свои закреплённые чертежи нужно выполнить следующее:
- Открыть файл "%localappdata%/odyssey-materials-helper/pref.properties" текстовым редактором (блокнот и ему подобные)
- Заменить строчку "language=RUSSIAN" на "language=ENGLISH"
- Сохранить файл.
Пока что данная локализация сломана.

**Comment by jixxed** [comment]
thnx for reporting. fixed in 2.96
was missing a comma in the translations csv file
