### ISSUE TITLE
Gentoo, can't run the app

### ISSUE THREAD

**Issue by Optimus22Prime** [jixxed/ed-odyssey-materials-helper#61]
Hello, I can't run Elite.Dangerous.Odyssey.Materials.Helper-1.55.portable.linux.zip. I'm unzip archive to EDOMH directory, run ./bin/Elite\ Dangerous\ Odyssey\ Materials\ Helper and got this:

Exception in thread "main" java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.base/java.lang.reflect.Method.invoke(Unknown Source)
        at java.base/sun.launcher.LauncherHelper$FXHelper.main(Unknown Source)
Caused by: java.lang.ExceptionInInitializerError
        at nl.jixxed.eliteodysseymaterials/nl.jixxed.eliteodysseymaterials.domain.ApplicationState.<init>(Unknown Source)
        at nl.jixxed.eliteodysseymaterials/nl.jixxed.eliteodysseymaterials.domain.ApplicationState.getInstance(Unknown Source)
        at nl.jixxed.eliteodysseymaterials/nl.jixxed.eliteodysseymaterials.Main.<clinit>(Unknown Source)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.base/java.lang.reflect.Method.invoke(Unknown Source)
        at javafx.graphics/com.sun.javafx.application.LauncherImpl.launchApplicationWithArgs(Unknown Source)
        at javafx.graphics/com.sun.javafx.application.LauncherImpl.launchApplication(Unknown Source)
        ... 5 more
Caused by: java.lang.NullPointerException
        at java.base/java.io.File.<init>(Unknown Source)
        at nl.jixxed.eliteodysseymaterials/nl.jixxed.eliteodysseymaterials.service.PreferencesService.<clinit>(Unknown Source)
        ... 14 more

I use up to date Gentoo stable, no Java vm installed, presume "portable" means that package already have bundled java vm inside? If it's not, which version of Java VM I must install?

**Comment by Optimus22Prime** [comment]
So, I clone a repo and try to run\build it by myself That's what I get, now with string numbers instead (Unknown Source), because that's not so useful for debugging purposes. Anyway I know nothing about java development, but I may do some tests and can provide any needed info for you.

$ ./gradlew run

> Task :application:compileJava
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

> Task :application:run
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:567)
        at java.base/sun.launcher.LauncherHelper$FXHelper.main(LauncherHelper.java:1071)
Caused by: java.lang.ExceptionInInitializerError
        at nl.jixxed.eliteodysseymaterials/nl.jixxed.eliteodysseymaterials.domain.ApplicationState.<init>(ApplicationState.java:51)
        at nl.jixxed.eliteodysseymaterials/nl.jixxed.eliteodysseymaterials.domain.ApplicationState.getInstance(ApplicationState.java:72)
        at nl.jixxed.eliteodysseymaterials/nl.jixxed.eliteodysseymaterials.Main.<clinit>(Main.java:40)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:567)
        at javafx.graphics/com.sun.javafx.application.LauncherImpl.launchApplicationWithArgs(LauncherImpl.java:465)
        at javafx.graphics/com.sun.javafx.application.LauncherImpl.launchApplication(LauncherImpl.java:364)
        ... 5 more
Caused by: java.lang.NullPointerException
        at java.base/java.io.File.<init>(File.java:278)
        at nl.jixxed.eliteodysseymaterials/nl.jixxed.eliteodysseymaterials.service.PreferencesService.<clinit>(PreferencesService.java:34)
        ... 14 more
